version: '3.8'
 
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - frontend
 
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    networks:
      - backend
 
networks:
  frontend:
  backend:
