name: Test avec différentes versions de Node.js

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14', '16', '18']

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installation des dépendances
      run: npm install

    - name: Exécution des tests
      run: npm test
