name: Analyse de code et couverture de tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    # Installation des dépendances
    - name: Installer les dépendances
      run: npm install

    # Exécution des tests unitaires avec Jest
    - name: Tests unitaires
      run: npm test

    # Génération du rapport de couverture de tests avec Jest
    - name: Rapport de couverture de tests
      run: npm test -- --coverage
