name: Workflow avec déclenchement basé sur un dossier

on:
  push:
    paths:
      - 'test/*'
  pull_request:
    paths:
      - 'test/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Affichage du contenu de mon-dossier
      run: ls test/
