name: Rollback en cas d'échec du déploiement

on:
  deployment_status:
    types:
      - failure

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Rollback du déploiement
      run:       
        # Nous sommes dans un cas fictif donc nous n'avons pas de rollbakc a effectuer
        # cependant si il existait une application alors on reviendrait a une version precedente avec un git rebase
        echo "Effectuer le rollback du déploiement"

    - name: Notification du rollback
      run: |
        echo "Le rollback a été effectué en raison d'un échec du déploiement."
