name: Déploiement sur la branche de production avec notifications Slack

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
  
  deploy:
    name: Deploy to Cloud
    runs-on: ubuntu-latest
    needs: build
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Deploy to Cloud
        run: |
          docker-compose up -d
     
      - name: Stop container
        run: |
          docker-compose down
    
  notify-slack:
    name: Notify on Slack
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ always() }}
 
    steps:
      - name: Notify on Slack
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          text: "Tests ${{ job.status }} on branch ${{ github.ref }} in repository ${{ github.repository }}"
        env:
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
